title: Sanghyun's steady stack.
description: > # this means to ignore newlines until "baseurl:"
  "Slow but steady wins the race."
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tlonist-sang.github.io"  # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Sanghyun Harry Kim # add your name
author-img: sanghyun.jpg # add your photo
about-author: Web developer. Love Go, Borges, and Gym
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github:  # add your Github handle
social-linkedin: sanghyun-harry-kim
social-email: tlonist.sang@gmail.com

#category
category_dir: categories/

#tag
tag_dir: tag/

# Disqus
discus-identifier: mr-brown # add your discus identifier
disqus:
  shotname: steadystack
# Tracker
analytics: UA-139982514-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
